
# --- Bordes Redondeados ---
corner-radius = 10;

# Evitar redondear ventanas específicas
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

# --- Motor Grafico ---
backend = "xrender"

# --- Sombras ---
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'i3-frame'",
	"class_g = 'i3bar'"
];

# --- Transparencias ---
inactive-opacity = 0.85;
active-opacity = 0.95;
frame-opacity = 1.0;

# --- Reglas extra ---
opacity-rule = [
	"100:class_g = 'firefox'" # asi el firefox no se pone transparente tambien xd
];

